import {
  BrowserKVStore,
  HttpAssetStore,
  HttpDocumentStore,
  type HttpAssetHeadersHook,
  type HttpDocumentHeadersHook,
} from '@openmaic/storage';
import { HttpRuntimeStore, type HttpRuntimeHeadersHook } from '@openmaic/storage/runtime/http';

import {
  assertDocumentStorageConfigurable,
  configureDocumentStorage,
  type DocumentStorageOptions,
} from '@/lib/document-store/config';
import {
  assertAssetPoolStorageConfigurable,
  configureAssetPoolStorage,
  type AssetPoolStorageOptions,
} from '@/lib/media/asset-pool-config';
import { assertRuntimeStorageConfigurable, configureRuntimeStorage } from '@/lib/runtime/config';
import { getLearnerKey } from '@/lib/runtime/learner-key';
import { parseSaasSession } from '@/lib/saas/session-state';

let deviceKv: BrowserKVStore | undefined;
let learnerKeyPromise: Promise<string> | undefined;

/** Set by the root layout before client modules run. Absent means SaaS is off. */
export function isSaasBrowserEnabled(): boolean {
  if (typeof window === 'undefined') return false;
  return (window as Window & { __OPENMAIC_SAAS__?: boolean }).__OPENMAIC_SAAS__ === true;
}

export function isBrowserPersistenceEnabled(): boolean {
  return (
    typeof window !== 'undefined' &&
    (process.env.NEXT_PUBLIC_PERSISTENCE === '1' || isSaasBrowserEnabled())
  );
}

async function saasUserLearnerKey(): Promise<string> {
  const response = await fetch('/api/saas/session', { credentials: 'include', cache: 'no-store' });
  const body = await response.json().catch(() => null);
  const session = parseSaasSession(response.status, body);
  if (session.status !== 'signed-in') {
    throw new Error('SaaS runtime requires a signed-in user');
  }
  return session.account.userId;
}

export function getPersistenceLearnerKey(): Promise<string> {
  if (!isBrowserPersistenceEnabled()) {
    return Promise.reject(new Error('Browser persistence is not enabled'));
  }
  // The server binds runtime rows to the session user. An anonymous device key
  // is a different partition, and the quiz page stays blank when that read is refused.
  if (isSaasBrowserEnabled()) {
    return (learnerKeyPromise ??= saasUserLearnerKey().catch((error) => {
      learnerKeyPromise = undefined;
      throw error;
    }));
  }
  return (learnerKeyPromise ??= getLearnerKey((deviceKv ??= new BrowserKVStore())).catch(
    (error) => {
      learnerKeyPromise = undefined;
      throw error;
    },
  ));
}

export async function getPersistenceRequestHeaders(): Promise<Record<string, string>> {
  if (!isBrowserPersistenceEnabled()) return {};
  // SaaS identity is the session cookie. A client learner key or dev token must not ride along.
  if (isSaasBrowserEnabled()) return {};
  const resolvedLearnerKey = await getPersistenceLearnerKey();
  const token = process.env.NEXT_PUBLIC_PERSISTENCE_TOKEN;
  return {
    'x-learner-key': resolvedLearnerKey,
    ...(token ? { authorization: `Bearer ${token}` } : {}),
  };
}

if (isBrowserPersistenceEnabled()) {
  const learnerKey = getPersistenceLearnerKey;
  const headers = getPersistenceRequestHeaders;

  const runtimeOptions = {
    store: () =>
      new HttpRuntimeStore({
        baseUrl: '/api/persistence',
        headers: headers satisfies HttpRuntimeHeadersHook,
      }),
    learnerKey,
  };
  const documentOptions: DocumentStorageOptions = {
    store: ({ validateScene, validateStage }) =>
      new HttpDocumentStore({
        baseUrl: '/api/persistence',
        headers: headers satisfies HttpDocumentHeadersHook,
        validateScene,
        validateStage,
      }),
  };
  // The document outlives the browser that produced it, so the media it
  // references must too: generated bytes go to the same endpoint under the
  // same credentials, and the document holds the id the pool allocated.
  // `serverBacked` is what tells local-cache cleanup that these refs are not
  // this browser's to delete.
  const assetOptions: AssetPoolStorageOptions = {
    store: () =>
      new HttpAssetStore({
        baseUrl: '/api/persistence',
        headers: headers satisfies HttpAssetHeadersHook,
      }),
    serverBacked: true,
  };
  try {
    // All checks are mutation-free. Once they pass, the synchronous configure
    // calls cannot leave only a subset of the persistence seams configured.
    assertRuntimeStorageConfigurable();
    assertDocumentStorageConfigurable();
    assertAssetPoolStorageConfigurable();
    configureRuntimeStorage(runtimeOptions);
    configureDocumentStorage(documentOptions);
    configureAssetPoolStorage(assetOptions);
  } catch (error) {
    console.error(
      'FATAL: server-backed persistence bootstrap failed; no storage seam changes were applied',
      error,
    );
  }
}
